export const URL = {
    auth: '/secure/login',
    searchEmailJobForPlanTrip: '/searchEmailJobForPlanTrip',

    searchCustomer: '/org/searchCustomer',
    searchGasolineByCust: '/org/searchGasolineByCust',
    searchGasoline: '/org/searchGasoline',
    addMeter: '/org/addMeter',
    updMeter: '/org/updMeter',
    cancelMeter: '/org/cancelMeter',

    searchLoc: '/org/searchLoc',
    searchProvince: '/org/searchProvince',
    searchLocType: '/org/searchLocType',
    addLoc: '/org/addLoc',
    updLoc: '/org/updLoc',
    cancelLoc: '/org/cancelLoc',

    searchMyAccount: '/searchMyAccount',
    searchProspectRecommend:'/searchProspectRecommend',
    searchAccountInTerritory:'/searchAccountInTerritory',
    searchBrand: '/org/searchBrand',
    getConfigLov:'/org/getConfigLov',
    searchDistrict: '/org/searchDistrict',
    searchSubDistrict: '/org/searchSubDistrict',
    createProspect: '/createProspect',
    searchProspectAddress: '/searchProspectAddress',
    searchProspectSaTab: '/searchProspectSaTab ',
    searchSalesTerritoryTab: '/searchSalesTerritoryTab',
    searchRecommendBuTab: '/searchRecommendBuTab',
    searchBusinessUnit:'/org/searchBusinessUnit',
    addProspectRecommend:'/addProspectRecommend',
    delProspectRecommend:'/delProspectRecommend',
    searchFeedTab: '/searchFeedTab',
    searchBrandCate:'/org/searchBrandCate',
    searchRegion: '/org/searchRegion',
    updProspectSaTab: '/updProspectSaTab',
    searchProspectContact: '/searchProspectContact',
    addContact: '/addContact',
    updContact: '​/updContact',
    delContact: '​/delContact',
    searchServiceType:'/org/searchServiceType',
    searchTemplateSaResultTab:'/searchTemplateSaResultTab',
    viewTemplateSaResult:'/viewTemplateSaResult',
    getTerritoryForDedicated:'/getTerritoryForDedicated',
    addProspectDedicated:'/addProspectDedicated',
    delProspectDedicated:'/delProspectDedicated',
    searchVisitHour:'/searchVisitHour',
    addVisitHour:'/addVisitHour',
    delVisitHour:'/delVisitHour',
    updProspectDbdTab: '/updProspectDbdTab',
    searchOtherProspect:'/searchOtherProspect',
    updProspectBasicTab: '/updProspectBasicTab',
    cloneProspect:'/cloneProspect',
    searchSaleOrderTab:'/searchSaleOrderTab',
    searchStockCountTab:'/searchStockCountTab',
    searchSaleDataTab:'/searchSaleDataTab',
    searchRecordMeterTab:'/searchRecordMeterTab',
    searchSurveyResultTab:'/searchSurveyResultTab',
    viewSurveyResult:'/viewSurveyResult',
    searchAttachCate:'/org/searchAttachCate',
    searchAttachmentTab:'/searchAttachmentTab',
    searchPlanTripForSaleVisit:'/searchPlanTripForSaleVisit',
    viewPlanTrip:'/viewPlanTrip',
    viewPlanTripTask:'/viewPlanTripTask',
    searchPlanTrip: '/searchPlanTrip',
    getEmpForAssignPlanTrip: '​/getEmpForAssignPlanTrip',
    getProspectForCreatePlanTrip: '/getProspectForCreatePlanTrip',
    getTaskMeterForRecord:'/getTaskMeterForRecord',
    uploadFileMeter:'/uploadFileMeter',
    searchMeter:'/searchMeter',
    addRecordMeter:'/addRecordMeter',
    taskTemplateAppForm:'/getTaskTemplateAppFormForRecord',
    addRecordAppForm:'/addRecordAppForm',
    uploadFileAppForm:'/uploadFileAppForm',
    getTaskStockCardForRecord:'/getTaskStockCardForRecord',
    addRecordStockCard:'/addRecordStockCard',
    getMasterDataForTemplateSa:'/getMasterDataForTemplateSa',
    getTaskTemplateSaFormForRecord:'/getTaskTemplateSaFormForRecord',
    uploadFileSaForm:'/uploadFileSaForm',
    addRecordSaForm:'/addRecordSaForm',
    updProspectSaTab: '/updProspectSaTab',
    importProspect: '/importProspect',
    searchSaleOrder:'/searchSaleOrder',
    searchOrderDocType:'/searchOrderDocType',
    searchShipToByCustSaleId:'/searchShipToByCustSaleId',
    searchCustomerSaleByCustCode:'/searchCustomerSaleByCustCode',
    createSaleOrder:'/createSaleOrder',
    cancelSaleOrder:'/cancelSaleOrder',
    getTaskTemplateAppFormForCreatPlan: '/getTaskTemplateAppFormForCreatPlan',
    getTaskSpecialForCreatPlan: '/getTaskSpecialForCreatPlan',  
    createPlanTrip: '/createPlanTrip',
    updPlanTrip: '/updPlanTrip',
    mergPlanTrip: '​/mergPlanTrip',
    cancelPlanTrip: '/cancelPlanTrip',
    rejectPlanTrip: '/rejectPlanTrip',
    approvePlanTrip: '/approvePlanTrip',
    getConfigParam:'/org/getConfigParam',
    searchLoc:'/org/searchLoc',
    planTripStart:'/planTripStart',
    searchProductByPlantCode: '/searchProductByPlantCode',
    searchProductByCustSaleId: '/searchProductByCustSaleId',
    searchProductConversion: '/searchProductConversion',
    updSaleOrder: '/updSaleOrder',
    delSaleOrder: '/delSaleOrder',
    searchPlantByCompanyCode:'/searchPlantByCompanyCode',
    searchOrderReason:'/searchOrderReason',
    searchShippingPointByPlantCode:'/searchShippingPointByPlantCode',
    searchCompany:'/searchCompany',
    getSaleOrderByOrderId:'/getSaleOrderByOrderId',
    planTripFinish:'/planTripFinish',
    getLastCheckIn:'​/getLastCheckIn',
    checkInPlanTripProspect:'/checkInPlanTripProspect',
    searchPlanReasonNotVisit:'/org/searchPlanReasonNotVisit',
    updateRemindForProspect:'/updateRemindForProspect',
    checkOutPlanTripProspect:'/checkOutPlanTripProspect',
    updateLocRemarkForProspect:'/updateLocRemarkForProspect',
    getProspectForCreatePlanTripAdHoc:'/getProspectForCreatePlanTripAdHoc',
    addPlanTripProspectAdHoc:'/addPlanTripProspectAdHoc',
    getTaskTemplateAppFormForCreatPlan:'/getTaskTemplateAppFormForCreatPlan',
    getTaskSpecialForCreatPlan:'/getTaskSpecialForCreatPlan',
    addPlanTripTaskAdHoc:'/addPlanTripTaskAdHoc',
    searchOrderIncoterm:'/searchOrderIncoterm',
    searchSaleOrderDocFlow: '/searchSaleOrderDocFlow',
    searchSaleOrderChangeLog :'/searchSaleOrderChangeLog',
    createSaleOrderByQuotationNo:'/createSaleOrderByQuotationNo',
    updReasonNotVisitForProspect:'/updReasonNotVisitForProspect',
    checkPercentRangRecordMeter:'/checkPercentRangRecordMeter',
    getLastRemindPlanTripProspect:'/getLastRemindPlanTripProspect',

    getUserProfile:'/secure/getUserProfile',
    getNotifyTabOverview: '/getNotifyTabOverview',
    delProspect: '/delProspect',

    delPlanTripProspectAdHoc: '/delPlanTripProspectAdHoc',
    delPlanTripTaskAdHoc: '/delPlanTripTaskAdHoc',

}
